version: '3'
services:
  db:
    container_name: db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: mydb
  app:
    container_name: app
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db